EXCEL_INPUT_PATH = 'Mochila_capacidad_maxima_20kg.xlsx'
EXCEL_SHEET_NAME = 'Hoja1'
EXCEL_RESULT_PATH = 'Resultados.xlsx'

PESO_MAXIMO = 20000
NUM_HORMIGAS = 80
NUM_ITERACIONES = 80
EVAPORACION = 0.4
FEROMONA_INICIAL = 0.7
ALPHA = 0.3
BETA = 0.3
