EXCEL_INPUT_PATH = 'Mochila_capacidad_maxima_20kg.xlsx'
EXCEL_SHEET_NAME = 'Hoja1'
EXCEL_RESULT_PATH = 'Resultados.xlsx'

PESO_MAXIMO = 20000
NUM_HORMIGAS = 20
NUM_ITERACIONES = 100
EVAPORACION = 0.1
FEROMONA_INICIAL = 0.9
ALPHA = 1
BETA = 0.5
